### PR TITLE
Me readme update

### PR DESCRIPTION
**Pull request by markellisdev**
##Pull Requests

##Descriptions:

* Please describe what issue this PR solves
This addresses the file path in Step 2 of the README
re Issue #53 

##Steps to Test:

1. Create a test directory somewhere outside of your project
2. Follow steps in the README to clone and run application inside that test directory

##System configuration.

* Are there 3rd party libraries that need to be installed?
None needed

* Any command line utilities to run?
See README

### CODE REVIEW

**Review by whitneycormack — APPROVED** [review]
👍

**Comment by markellisdev** [comment]
Still needs one more step. Coming up.... Hold on

**Comment by markellisdev** [comment]
Please make sure this works on your machine. I have tested it on my own and it works here, but of course it needs to work for everyone.

**Comment by whitneycormack** [comment]
👍

**Pull request merged**
