### PR TITLE
customer model extends User

### PR DESCRIPTION
**Pull request by markellisdev**
##Pull Requests

##Descriptions:

* Please describe what issue this PR solves
This creates a Customer model, which is an extension of the User model.
Issue #39  

The Customer model provides the following necessary fields to User.
⋅⋅*address
⋅⋅*city
⋅⋅*state_province
⋅⋅*country
⋅⋅*payment_type

This information is necessary for company operations, such as shipping, contacting customers, and keeping track of payment types per user.

Prior to this code, we could not capture all necessary information for customers. This should provide all necessary information in the User view.

##Steps to Test:

1. git fetch
2. checkout me-userExtend
3. python manage.py shell
4. While in shell
⋅⋅* import User model 
⋅⋅* import Customer model 
⋅⋅* create a user variable and pass in name, email, password to User model
⋅⋅* create a Customer model passing in the created user
⋅⋅* confirm that values are as input
5. Perform migrations
⋅⋅* python manage.py makemigrations
⋅⋅* python manage.py migrate
6. Open localhost:8000 and navigate to User view to confirm your user has been created with the necessary fields

##System configuration.

* Are there 3rd party libraries that need to be installed?
No 3rd party libraries necessary

* Any command line utilities to run?
See above instructions

In the UI
1. Login to your superuser
2. Select the link for Users
3. Confirm that Users contains the information specified in this PR

### CODE REVIEW

**Comment by markellisdev** [comment]
I didn't have a Customer view showing correctly originally. My apologies. The new commit corrects that. Please confirm that you are now able to view and update customers. The payment_type selection in that view is not working correctly yet, for me anyway, but I suspect I loaded mine incorrectly. Please check this and see what results you get. Thanks!

**Comment by markellisdev** [comment]
I'm also realizing the Customer view should have been a separate issue.

**Comment by ghost** [comment]
Still only seeing the User fields...

**Comment by ghost** [comment]
Looks good.  Customer extends user profile.  👍

**Pull request merged**
